"""
pcbstatorgen.geometry.end_turn
=====================================
End-turn routing specifications and helpers.

What are end-turns?
-------------------
End-turns are the horizontal conductor segments at the top (``y = board_width``)
and bottom (``y = 0``) edges of the PCB that connect successive active
conductors of the same phase.  They are already present in the polylines
generated by :class:`~pcbstatorgen.geometry.wave_winding.WaveWindingGenerator`
as segments with ``is_active = False``.

This module provides:

* :class:`EndTurnSpec` — a richer description of one end-turn location that
  adds the associated :class:`~pcbstatorgen.geometry.via_grid.ViaGrid` and
  routing metadata.
* :class:`EndTurnRouter` — groups the end-turn segments of all phase coils and
  attaches via grids to each one.

End-turn overlap and layer isolation
-------------------------------------
Adjacent phases have end-turns that **overlap in the X range** because the
phases are offset by only ``slot_pitch = pole_pitch / phases``.  For example,
with a 12 mm pole pitch and 3 phases (slot pitch = 4 mm):

* Phase A end-turn at y=W: x = 0 → 12 mm
* Phase B end-turn at y=W: x = 4 → 16 mm   ← overlaps A by 8 mm!
* Phase C end-turn at y=W: x = 8 → 20 mm   ← overlaps A and B!

Physically, these **must** be on separate copper layers.  The
:class:`EndTurnRouter` records which layer each end-turn belongs to (taken
from the parent :class:`~pcbstatorgen.geometry.wave_winding.PhaseCoil`)
so that the KiCad writer can verify layer isolation.

Via region width
-----------------
Because vias must sit inside valid copper (the end-turn trace), the available
via placement depth in Y is less than the full board width.  The default is
``END_TURN_VIA_REGION_M = 2 mm`` from each edge.  For narrower boards this is
clamped to ``board_width / 4``.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field

from pcbstatorgen.config import MotorConfig
from pcbstatorgen.geometry.via_grid import ViaGrid, ViaGridGenerator
from pcbstatorgen.geometry.wave_winding import CoilSegment, PhaseCoil

__all__ = [
    "EndTurnSide",
    "EndTurnSpec",
    "EndTurnRouter",
    "END_TURN_VIA_REGION_M",
]

#: Default via placement depth near board edges [m].
END_TURN_VIA_REGION_M: float = 2e-3  # 2 mm


# ---------------------------------------------------------------------------
# Enums and dataclasses
# ---------------------------------------------------------------------------


class EndTurnSide(enum.Enum):
    """Which edge of the board an end-turn sits on."""

    TOP = "top"
    """End-turn at ``y = board_width`` (top edge when X is the travel axis)."""

    BOTTOM = "bottom"
    """End-turn at ``y = 0`` (bottom edge)."""


@dataclass
class EndTurnSpec:
    """Full specification for one end-turn segment and its via grid.

    Parameters
    ----------
    segment:
        The :class:`~pcbstatorgen.geometry.wave_winding.CoilSegment`
        (always ``is_active = False``) that this spec describes.
    phase_idx:
        Phase index of the parent coil (0 = A, 1 = B, 2 = C, …).
    layer_idx:
        PCB layer of the parent coil.
    side:
        Whether this end-turn is at the top or bottom board edge.
    via_grid:
        Via grid placed at the midpoint of this end-turn for inter-layer
        current transfer.  ``None`` for single-layer windings where no
        layer transition is required at this end-turn.
    """

    segment: CoilSegment
    phase_idx: int
    layer_idx: int
    side: EndTurnSide
    via_grid: ViaGrid | None = None

    @property
    def length_m(self) -> float:
        """Length of the end-turn segment [m]."""
        return self.segment.length_m

    @property
    def midpoint(self) -> tuple[float, float]:
        """Midpoint ``(x, y)`` of the end-turn segment [m]."""
        return self.segment.midpoint

    @property
    def x_start(self) -> float:
        """X position of the start of the end-turn [m]."""
        return self.segment.start[0]

    @property
    def x_end(self) -> float:
        """X position of the end of the end-turn [m]."""
        return self.segment.end[0]

    @property
    def y_position(self) -> float:
        """Y position of the end-turn (constant along its length) [m]."""
        return self.segment.start[1]


# ---------------------------------------------------------------------------
# Router
# ---------------------------------------------------------------------------


class EndTurnRouter:
    """Compute end-turn specs and attach via grids to each end-turn.

    Parameters
    ----------
    via_region_width_m:
        Depth of the via placement zone at each board edge [m].
        Clamped to ``board_width / 4`` for narrow boards.
        Default: 2 mm.
    via_generator:
        :class:`~pcbstatorgen.geometry.via_grid.ViaGridGenerator` to use.
        If ``None``, a default generator with standard parameters is created.
    """

    def __init__(
        self,
        via_region_width_m: float = END_TURN_VIA_REGION_M,
        via_generator: ViaGridGenerator | None = None,
    ) -> None:
        if via_region_width_m <= 0:
            raise ValueError(
                f"via_region_width_m must be positive, got {via_region_width_m}"
            )
        self.via_region_width_m = via_region_width_m
        self.via_generator = via_generator or ViaGridGenerator()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def compute_end_turn_specs(
        self,
        coils: list[PhaseCoil],
        config: MotorConfig,
        attach_via_grids: bool = True,
    ) -> list[EndTurnSpec]:
        """Build :class:`EndTurnSpec` objects for every end-turn in every coil.

        Parameters
        ----------
        coils:
            Phase coils from :class:`~pcbstatorgen.geometry.wave_winding.WaveWindingGenerator`.
        config:
            Motor config (board width, current, DFM constraints).
        attach_via_grids:
            If ``True`` (default), generate and attach a
            :class:`~pcbstatorgen.geometry.via_grid.ViaGrid` to each
            spec.  Set to ``False`` for single-layer windings where no via
            grids are needed.

        Returns
        -------
        list[EndTurnSpec]
            All end-turn specs, ordered by layer → phase → coil position.
        """
        specs: list[EndTurnSpec] = []
        via_y = self._effective_via_region_width(config)

        for coil in coils:
            for seg in coil.end_turn_segments:
                side = self._classify_side(seg, config)
                spec = EndTurnSpec(
                    segment=seg,
                    phase_idx=coil.phase_idx,
                    layer_idx=coil.layer_idx,
                    side=side,
                    via_grid=None,
                )
                if attach_via_grids:
                    spec.via_grid = self.via_generator.generate_for_end_turn(
                        center=seg.midpoint,
                        available_x_m=seg.length_m,
                        available_y_m=via_y,
                        current_a=config.max_current_a,
                        config=config,
                    )
                specs.append(spec)

        return specs

    def check_layer_conflicts(
        self,
        specs: list[EndTurnSpec],
        tol: float = 1e-9,
    ) -> list[tuple[EndTurnSpec, EndTurnSpec]]:
        """Find pairs of end-turns on the same layer and same Y edge that overlap in X.

        An overlap means the two end-turns share physical PCB space on the same
        copper layer, which would cause a short circuit.

        Parameters
        ----------
        specs:
            All end-turn specs to check.
        tol:
            Minimum overlap length to report [m].

        Returns
        -------
        list[tuple[EndTurnSpec, EndTurnSpec]]
            Conflicting pairs.  Empty list if no conflicts are found.
        """
        conflicts: list[tuple[EndTurnSpec, EndTurnSpec]] = []
        for i, s1 in enumerate(specs):
            for s2 in specs[i + 1 :]:
                if s1.layer_idx != s2.layer_idx:
                    continue
                if s1.side != s2.side:
                    continue
                # Check X range overlap
                x_lo = max(s1.x_start, s2.x_start)
                x_hi = min(s1.x_end, s2.x_end)
                if x_hi - x_lo > tol:
                    conflicts.append((s1, s2))
        return conflicts

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _effective_via_region_width(self, config: MotorConfig) -> float:
        """Return the usable via placement depth at each board edge [m].

        Clamped to ``board_width / 4`` for narrow boards.
        """
        return min(self.via_region_width_m, config.board_width_m / 4.0)

    @staticmethod
    def _classify_side(seg: CoilSegment, config: MotorConfig) -> EndTurnSide:
        """Determine whether an end-turn is at the top or bottom board edge."""
        mid_y = (seg.start[1] + seg.end[1]) / 2.0
        return (
            EndTurnSide.TOP
            if mid_y > config.board_width_m / 2.0
            else EndTurnSide.BOTTOM
        )
